export const theme = {
  colors: {
    primary: "#3366FF",
    secondary: "#FF6600",
    background: "#F4F5F8",
    cardBackground: "#FFFFFF",
    white: "#FFFFFF",
    black: "#000",
    headerBackground: "#EBECF0",
    headerBackgroundHover: "#DBDCE0",
    text: "#333333",
    mutedText: "#7A7A7A",
    border: "#E0E0E0",
    actionBackground: "#FFFFFF",
    actionHover: "#DFE1E6",
    borderLight: "#EDEEF0",
    textMuted: "#6B6F76",
    textDark: "#282A30",
    badge: {
      urgent: "#FF4D4D",
      high: "#FF9933",
      medium: "#FFD700",
      low: "#87D068",
      noPriority: "#C0C0C0",
    },
  },
  borderRadius: {
    small: "4px",
    medium: "8px",
  },
  spacing: {
    xsmall: "4px",
    small: "8px",
    medium: "16px",
    large: "32px",
  },
  fonts: {
    main: "Arial, sans-serif",
    size: "16px",
    small: "12px",
    xsmall: "10px",
    weight: {
      normal: 400,
      bold: 700,
    },
  },
  shadows: {
    button: "0 2px 4px rgba(0, 0, 0, 0.1)",
    card: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
};
